config/routes.rb
Rails.application.routes.draw do
  resources :excursions
  resources :tours do
    collection do
      get :search
    end
  end
  resources :routes
  resources :cities
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
    collection do
      post :create_by_admin
      get :new_by_admin
    end
  end

end

app/models/tour.rb
class Tour < ActiveRecord::Base
  belongs_to :route
  validates :date_start, presence: true
  validates :count_days, presence: true, numericality: {greater_than_or_equal_to: 0}
  validates :add_pay, presence: true, numericality: {greater_than: 0}
  validates :add_description, presence: true

  accepts_nested_attributes_for :route, allow_destroy: true

  def self.search(params)
    result = Tour.includes(:route => :city).references(:city)

    if params['route'].present?
      result = result.where(routes: {name: params['route']})
    end
    if params['city_name'].present?
      result = result.where(cities: {name: params['city']})
    end

    if params['date_start'].present?
      result = result.where(date_start: Date.parse(params['date_start']))
    end
    if params['count_days'].present?
      result = result.where(count_days: params['count_days'])
    end

    if params['description'].present?
      result = result.where(routes: {description: params['description']})
    end

    if params['add_description'].present?
      result = result.where(add_description: params['add_description'])
    end
    
    if params['price'].present?
      result = result.where(routes: {price: params['price']})
    end
    if params['add_pay'].present?
      result = result.where(add_pay: params['add_pay'])
    end
    result.all
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:show, :edit, :update, :destroy]
  before_action :get_routes, only: [:edit, :update]
  skip_before_action :check_app_auth, only: [:index, :show]

  # GET /tours
  # GET /tours.json
  def index
    @tours = Tour.includes(:route).references(:route)
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
  end

  def search
    if params.has_key?('search')
      @tours = Tour.search(params['search'])
    else
      @tours = []
    end
    params['search'] ||= {}
  end

  # GET /tours/new
  def new
    @tour = Tour.new
  end

  # GET /tours/1/edit
  def edit
  end

  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.new(tour_params)

    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: 'Tour was successfully created.' }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update
    respond_to do |format|
      if @tour.update(tour_params)
        format.html { redirect_to @tour, notice: 'Tour was successfully updated.' }
        format.json { render :show, status: :ok, location: @tour }
      else
        format.html { render :edit }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    if @tour.route.tours.size == 1
      @tour.route.city.destroy if (@tour.route.city.routes.size ==1) && (@tour.route.city.excursions.size == 0)
      @tour.route.destroy 
    end
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: 'Tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_params
      params.require(:tour).permit(:route_id, :date_start, :count_days, :add_pay, :add_description,
        route_attributes: [:name, :city_id, :description, :price, :id, :_destroy,
          city_attributes: [:name, :id, :_destroy]]
      )
    end

    def get_routes
      @routes = Route.all
    end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/_city_edit_form.html.haml
.form-group.city-new.city-edit
  = route.fields_for :city, route.object.build_city do |city|
    = city.hidden_field(:id, class: 'city-id')
    = city.label :name
    = city.text_field :name, class: 'form-control city-name'

app/views/tours/_city_new_form.html.haml
.form-group.city-new.city-edit
  = route.fields_for :city, City.new do |city|
    = city.hidden_field(:id)
    = city.label :name
    = city.text_field :name, class: 'form-control'

app/views/tours/_city_select_form.html.haml
.form-group.city-select
  = route.label :city
  = route.select(:city_id, options_for_select(City.pluck('name, id'), route.object.city_id), {}, class: 'form-control select-city')

app/views/tours/_form.html.haml
= form_for @tour do |f|
  - if @tour.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tour.errors.count, "error")} prohibited this tour from being saved:"
      %ul
        - @tour.errors.full_messages.each do |message|
          %li= message

  .row
    .col-md-4
      .form-group
        = f.label :date_start
        .input-group.date.datepicker
          = f.text_field(:date_start, value: (f.object.date_start.strftime('%d.%m.%Y') if !f.object.new_record?), class: 'form-control')
          %span.input-group-addon
            %span.glyphicon.glyphicon-calendar
    .col-md-4
      .form-group
        = f.label :count_days
        = f.number_field :count_days, class: 'form-control'
    .col-md-4
      .form-group
        = f.label :add_pay
        = f.number_field :add_pay, class: 'form-control'
  .row
    .col-md-12
      .form-group
        = f.label :add_description
        = f.text_field :add_description, class: 'form-control'
  .row
    .col-md-12
      %h3 Выберите маршрут
      %span.toright
        = link_to_new_route()
        - if !f.object.new_record?
          = link_to_edit_route()
      = render('route_select_form', f: f)
      %div{class: "edit_form", "data-content" => "#{render "route_edit_form", f: f}"}
      %div{class: "new_form", "data-content" => "#{render "route_new_form", f: f}"}
      %div{class: "select_form", "data-content" => "#{render "route_select_form", f: f}"}


  .form-actions.bottom20
    = f.submit nil, class: 'btn btn-primary'

.for_update_fields
  - if @routes
    - @routes.each do |route|
      %div{class: "name-#{route.id}", data: {content: "#{route.name}"}  }
      %div{class: "description-#{route.id}", data: {content: "#{route.description}"}  }
      %div{class: "price-#{route.id}", data: {content: "#{route.price}"}  }
      %div{class: "city_id-#{route.id}", data: {content: "#{route.city_id}"}  }
      %div{class: "city_name-#{route.id}", data: {content: "#{route.city.name}"}  }

app/views/tours/_route_edit_form.html.haml
.route-edit
  = f.fields_for :route do |route|
    = render "route_form", route: route
  

app/views/tours/_route_form.html.haml
= route.hidden_field(:id, class: "route_id")
.form-group
  = route.label :name
  = route.text_field :name, class: 'form-control route_name'
%span.toright
  = link_to_edit_city()
  = link_to_new_city()
= render("city_select_form", route: route)
%div{class: "new_form_city", "data-content"=>"#{render "city_new_form", route: route}"}
%div{class: "edit_form_city", "data-content"=>"#{render "city_edit_form", route: route}"}
%div{class: "select_form_city", "data-content"=>"#{render "city_select_form", route: route}"}


.form-group
  = route.label :description
  = route.text_field :description, class: 'form-control route_description'
.form-group
  = route.label :price
  = route.number_field :price, step: 0.01, class: 'form-control route_price'

app/views/tours/_route_new_form.html.haml
.route-new
  = f.fields_for :route, Route.new do |route|
    = render "route_form", route: route

app/views/tours/_route_select_form.html.haml
.form-group.route-select
  = f.label :route
  = f.select(:route_id, options_for_select(Route.pluck('name, id'), f.object.route_id), {},{ class: 'form-control select-route', onchange: 'update_fields(this)'})
.form-group.route-select
  = f.fields_for(:route, include_id: false) do |route|
    .form-group
      = route.label :city
      %i{class: 'upd-rcity'} #{route.object.city.name }
    .form-group
      = route.label :description
      %i{class: 'upd-rdescription'} #{route.object.description }
    .form-group
      = route.label :price
      %i{class: 'upd-rprice'} #{route.object.price }

app/views/tours/edit.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.tours.edit')
  %li
    = link_to @tour.route.name + @tour.date_start.strftime(" (%d.%m.%Y)"), @tour
  %li
    = link_to t('headers.tours.index'), tours_path()
  %li
    Главная

.page-header
  %h1= t('headers.tours.edit')
  %h3= @tour.route.name + @tour.date_start.strftime(" (%d.%m.%Y)")

= render 'form'

app/views/tours/index.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.tours.index')
  %li
    Главная

.page-header
  %h1= t('headers.tours.index')

%table.table.table-hover.table-striped
  %caption
    = link_to new_tour_path, class: 'btn btn-success' do
      = fa_icon :plus
      = t('buttons.new.tour') 
  %thead
    %tr
      %th= Tour.human_attribute_name(:route)
      %th= Tour.human_attribute_name(:date_start)
      %th= Tour.human_attribute_name(:count_days)
      %th= Tour.human_attribute_name(:add_pay)
      %th= Tour.human_attribute_name(:add_description)
      %th

  %tbody
    - @tours.each do |tour|
      %tr
        %td.center= tour.route.name
        %td.center= tour.date_start.strftime("%d.%m.%Y")
        %td.center= tour.count_days
        %td.center= tour.add_pay
        %td.center= tour.add_description
        %td.right
          = link_to tour, class: 'btn btn-warning' do
            = fa_icon :eye
            = t('buttons.show')
          = link_to edit_tour_path(tour), class: 'btn btn-info' do
            = fa_icon :edit
            = t('buttons.edit')
          = link_to tour, :method => :delete, 
          :data => { :confirm => t('buttons.confirm.tour') }, 
          class: 'btn btn-danger' do
            = fa_icon :times
            = t('buttons.destroy')

app/views/tours/new.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.tours.new')
  %li
    = link_to t('headers.tours.index'), tours_path()
  %li
    Главная
.page-header
  %h1= t('headers.tours.new')

= render 'form'

= link_to t('buttons.back'), tours_path, class: 'btn btn-default'

app/views/tours/search.html.haml
=breadcrumb_tag do
  %li.active
    Поиск
  %li
    = link_to t('headers.tours.index'), tours_path()
  %li
    Главная
.page-header
  %h1 Поиск

= form_tag search_tours_path(), method: :get do
  .row
    .col-md-6
      .form-group
        %b= Tour.human_attribute_name(:route)
        = text_field_tag 'search[route]', params['search']['route'], class: 'form-control'
    .col-md-6
      .form-group
        %b= Route.human_attribute_name(:city)
        = text_field_tag 'search[city]', params['search']['city'], class: 'form-control'
  .row
    .col-md-6
      .form-group
        %b= Tour.human_attribute_name(:date_start)
        .input-group.date.datepicker
          = text_field_tag 'search[date_start]', params['search']['date_start'], class: 'form-control'
          %span.input-group-addon
            %span.glyphicon.glyphicon-calendar
    .col-md-6
      .form-group
        %b= Tour.human_attribute_name(:count_days)
        = number_field_tag 'search[count_days]', params['search']['count_days'], class: 'form-control'
  .row
    .col-md-12
      .form-group
        %b= Route.human_attribute_name(:description)
        = text_field_tag 'search[description]', params['search']['description'], class: 'form-control'
  .row
    .col-md-12
      .form-group
        %b= Tour.human_attribute_name(:add_description)
        = text_field_tag 'search[add_description]', params['search']['add_description'], class: 'form-control'
  .row
    .col-md-6
      .form-group
        %b= Route.human_attribute_name(:price)
        = number_field_tag 'search[price]', params['search']['price'], step: 0.01,  class: 'form-control'

    .col-md-6
      .form-group
        %b= Tour.human_attribute_name(:add_pay)
        = number_field_tag 'search[add_pay]', params['search']['add_pay'], step: 0.01, class: 'form-control'



  = submit_tag 'Поиск', class: 'btn btn-primary'
%br
- if !@tours.empty?
  %table.table.table-hover.table-striped.table-adaptive
    %thead
      %tr
        %th= Tour.human_attribute_name(:route)
        %th= Route.human_attribute_name(:city)
        %th= Tour.human_attribute_name(:date_start)
        %th= Tour.human_attribute_name(:count_days)
        %th= Route.human_attribute_name(:description)
        %th= Tour.human_attribute_name(:add_description)
        %th= Route.human_attribute_name(:price)
        %th= Tour.human_attribute_name(:add_pay)
    %tbody
      - @tours.each do |tour|
        %tr.well
          %td{:data => {:label => "#{Tour.human_attribute_name(:route)}"}}
            = tour.route.name
          %td{:data => {:label => "#{Route.human_attribute_name(:city)}"}}
            = tour.route.city.name
          %td{:data => {:label => "#{Tour.human_attribute_name(:date_start)}"}}
            = tour.date_start.strftime('%d.%m.%Y')
          %td{:data => {:label => "#{Tour.human_attribute_name(:count_days)}"}}
            = tour.count_days
          %td{:data => {:label => "#{Route.human_attribute_name(:description)}"}}
            = tour.route.description
          %td{:data => {:label => "#{Tour.human_attribute_name(:add_description)}"}}
            = tour.add_description
          %td{:data => {:label => "#{Route.human_attribute_name(:price)}"}}
            = tour.route.price
          %td{:data => {:label => "#{Tour.human_attribute_name(:add_pay)}"}}
            = tour.add_pay
- else
  %h3 Ничего не найдено

app/views/tours/show.html.haml
=breadcrumb_tag do
  %li.active
    = @tour.route.name + @tour.date_start.strftime(" (%d.%m.%Y)")
  %li
    = link_to t('headers.tours.index'), tours_path()
  %li
    Главная

.page-header
  %h1= @tour.route.name + @tour.date_start.strftime(" (%d.%m.%Y)")
.row 
  .col-md-12
    %b= Tour.human_attribute_name(:route)
    %p= @tour.route.name
    
    %b= Tour.human_attribute_name(:date_start)
    %p= @tour.date_start.strftime("%d.%m.%Y")
    
    %b= Tour.human_attribute_name(:count_days)
    %p= @tour.count_days

    %b= Tour.human_attribute_name(:add_pay)
    %p= @tour.add_pay

    %b= Tour.human_attribute_name(:add_description)
    %p= @tour.add_description

= link_to edit_tour_path(@tour), class: 'btn btn-info' do
  = fa_icon :edit
  = t('buttons.edit')
= link_to t('buttons.back'), tours_path, class: 'btn btn-default'