config/routes.rb
Rails.application.routes.draw do
  resources :excursions
  resources :tours do
    collection do
      get :search
    end
  end
  resources :routes
  resources :cities
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
    collection do
      post :create_by_admin
      get :new_by_admin
    end
  end

end

app/models/excursion.rb
class Excursion < ActiveRecord::Base
  belongs_to :city

  validates :name, presence: true
  validates :city_id, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: {greater_than: 0}
end

app/controllers/excursions_controller.rb
class ExcursionsController < ApplicationController
  before_action :set_excursion, only: [:show, :edit, :update, :destroy]
  skip_before_action :check_app_auth, only: [:index, :show]

  # GET /excursions
  # GET /excursions.json
  def index
    @excursions = Excursion.includes(:city).references(:city)
  end

  # GET /excursions/1
  # GET /excursions/1.json
  def show
  end

  # GET /excursions/new
  def new
    @excursion = Excursion.new
  end

  # GET /excursions/1/edit
  def edit
  end

  # POST /excursions
  # POST /excursions.json
  def create
    @excursion = Excursion.new(excursion_params)

    respond_to do |format|
      if @excursion.save
        format.html { redirect_to @excursion, notice: 'Excursion was successfully created.' }
        format.json { render :show, status: :created, location: @excursion }
      else
        format.html { render :new }
        format.json { render json: @excursion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /excursions/1
  # PATCH/PUT /excursions/1.json
  def update
    respond_to do |format|
      if @excursion.update(excursion_params)
        format.html { redirect_to @excursion, notice: 'Excursion was successfully updated.' }
        format.json { render :show, status: :ok, location: @excursion }
      else
        format.html { render :edit }
        format.json { render json: @excursion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /excursions/1
  # DELETE /excursions/1.json
  def destroy
    @excursion.city.destroy if (@excursion.city.excursions.size == 1) && (@excursion.city.routes.size == 0)
    @excursion.destroy
    respond_to do |format|
      format.html { redirect_to excursions_url, notice: 'Excursion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_excursion
      @excursion = Excursion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def excursion_params
      params.require(:excursion).permit(:city_id, :name, :description, :price)
    end
end

app/helpers/excursions_helper.rb
module ExcursionsHelper
end

app/views/excursions/_form.html.haml
= form_for @excursion do |f|
  - if @excursion.errors.any?
    #error_explanation
      %h2= "#{pluralize(@excursion.errors.count, "error")} prohibited this excursion from being saved:"
      %ul
        - @excursion.errors.full_messages.each do |message|
          %li= message

  .row
    .col-md-4
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
    .col-md-4
      .form-group
        = f.label :city
        = f.select(:city_id, options_for_select(City.pluck("name, id"), f.object.city_id), {}, {class: 'form-control'})
    .col-md-4
      .form-group
        = f.label :price
        = f.number_field :price, step: 0.01, class: 'form-control'
  .row
    .col-md-12
      .form-group
        = f.label :description
        = f.text_field :description, class: 'form-control'
  .form-actions.bottom20
    = f.submit nil, class: 'btn btn-primary'

app/views/excursions/edit.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.excursions.edit')
  %li
    = link_to "#{@excursion.name}", @excursion
  %li
    = link_to t('headers.excursions.index'), excursions_path()
  %li
    Главная

.page-header
  %h1= t('headers.excursions.edit')


= render 'form'

= link_to t('buttons.back'), excursions_path, class: 'btn btn-default'

app/views/excursions/index.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.excursions.index')
  %li
    Главная

.page-header
  %h1= t('headers.excursions.index')

%table.table.table-hover.table-striped
  %caption
    = link_to new_excursion_path, class: 'btn btn-success' do
      = fa_icon :plus
      = t('buttons.new.excursion') 
  %thead
    %tr
      %th= Excursion.human_attribute_name(:name)
      %th= Excursion.human_attribute_name(:city)
      %th= Excursion.human_attribute_name(:price)
      %th= Excursion.human_attribute_name(:description)
      %th

  %tbody
    - @excursions.each do |excursion|
      %tr
        %td.center= excursion.name
        %td.center= excursion.city.name
        %td.center= excursion.price
        %td.center= excursion.description
        %td.right
          = link_to excursion, class: 'btn btn-warning' do
            = fa_icon :eye
            = t('buttons.show')
          = link_to edit_excursion_path(excursion), class: 'btn btn-info' do
            = fa_icon :edit
            = t('buttons.edit')
          = link_to excursion, :method => :delete, 
          :data => { :confirm => t('buttons.confirm.excursion') }, 
          class: 'btn btn-danger' do
            = fa_icon :times
            = t('buttons.destroy')

app/views/excursions/new.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.excursions.new')
  %li
    = link_to t('headers.excursions.index'), excursions_path()
  %li
    Главная

.page-header
  %h1= t('headers.excursions.new')

= render 'form'

= link_to t('buttons.back'), excursions_path, class: 'btn btn-default'

app/views/excursions/show.html.haml
=breadcrumb_tag do
  %li.active
    = @excursion.name
  %li
    = link_to t('headers.excursions.index'), excursions_path()
  %li
    Главная

.page-header
  %h1= @excursion.name
.row
  .col-md-12
    %b= Excursion.human_attribute_name(:city)
    %p= @excursion.city.name
    
    %b= Excursion.human_attribute_name(:price)
    %p= @excursion.price
    
    %b= Excursion.human_attribute_name(:description)
    %p= @excursion.description

= link_to edit_excursion_path(@excursion), class: 'btn btn-info' do
  = fa_icon :edit
  = t('buttons.edit')
= link_to t('buttons.back'), excursions_path, class: 'btn btn-default'